################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.c \
../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.c 

OBJS += \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.o \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.o 

C_DEPS += \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.d \
./Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_adc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_can.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_cec.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_comp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_crs.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dac.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dbgmcu.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_iwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_misc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_spi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_syscfg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.o: ../Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -g3 -DUSE_HAL_DRIVER -DSTM32F042x6 -DDEBUG -c -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Device/ST/STM32F0xx/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/Include" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/CMSIS/RTOS" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Libraries/STM32_F0xx_StdPerip_Driver/inc" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src/src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/Src" -I"C:/Users/SteDun00/Desktop/GitHub/LightShaker3_libUSB/USB/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32_F0xx_StdPerip_Driver/src/stm32f0xx_wwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

