/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialised, but the project is compiling for an FPU. Please initialise the FPU before use."
#endif

/* Includes */
#include "main.h"
#include "stm32f0xx_rcc.h"

#include "drvNvMemory.h"
#include "winusb_loop.h"
#include "drvDisplay.h"
#include "stdio.h"
#include "configConsole.h"
#include "drvPower.h"
#include "drvProgram.h"
#include "stm32f0xx_misc.h"
#include <drvSwitch.h>

/* Private typedef */

/* Private define  */

/* Private macro */

/* Private variables */

/* Private function prototypes */

/* Private functions */

/* Global variables */
uint32_t timer = 0;
uint8_t  timerFlag = 0;
volatile uint32_t delayTimer;
uint8_t led_pos;
int16_t levelResult;
uint8_t progselect = 0;
uint8_t errorcode = 0;
uint8_t tempstring[32];


/**
**===========================================================================
**
**  Abstract: SysTick interrupt handler
**
**===========================================================================
*/
void SysTick_Handler(void)
{
	if(delayTimer)
	{
		delayTimer--;
	}
	timer++;

	if  (timer>100)
	{
		timerFlag = 1;
		timer = 0;
	}
}


void delay(uint32_t ticks)
{
	delayTimer = ticks;
	while(delayTimer > 0);
}

/**
 * NOTES POV-Display:
 * When measuring the times for a complete frame
 * (time for the movement from turning point to turning point),
 * the minimal t_frame was about 70ms
 *
 * SPI Clock speed = 6MHz
 * a complete line has 576 bits to transmit
 * t_line_transmit = 96us
 * -> max 16x729 pixel theoretically
 * but the leds are only activated at the end of these 96us needed for transmitting, which would make it a bit complicated
 * -> no more than 16x64 pixels!!
 * for full color rgb, the complete frame already takes 3kB!
 */

int main(void)
{
	SystemInit();
	SystemCoreClockUpdate();
	//the systick timer runs with 6MHz
	//config the timer for 1ms interval
	SysTick_Config(SystemCoreClock / 8 / 1000);
	//the systick_config just set the priority of the systick to 15  or so - very low!
	//set it back to 0
	NVIC_SetPriority(SysTick_IRQn,0);
	SysTick_CLKSourceConfig(SysTick_CLKSource_HCLK_Div8);

	//init the drivers
	power_init();
	apa102_init();
	mma8653_init();

	globalColor.red=0xFF;
	globalColor.green=0xFF;
	globalColor.blue=0xFF;

	if(power_UsbPresent()) {
		//we are attached to a USB-Port!
		//USB_Init();
		winusb_init_usbd();
		usb_device_connect();
		consoleInit();
	}

	apa102_allOff();

	//LED-Test
	for(uint8_t i = 0; i<16; i++) {
		apa102_setSingle(i,10);
		delay(20);
	}

	switch(progselect) {
		case 0: init_povdisplay(); break;
		case 1: init_level(); break;
		case 2: init_test1(); break;
	}

	while(1) {
		switch(progselect) {
			case 0: povdisplay(); break;
			case 1: level(); break;
			case 2: test1(); break;
		}

		if(power_UsbPresent()){
			USB_Handler();
		}

		progselect = switch_exec(progselect);
	}
	return 0;
}
